apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-esll
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-esll
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-esll
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-esll
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-esll
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oaxk-tenant/rhtap-demo-app/hacbs-test-project-esll@sha256:a3cb098880ac4331e427f833014aa2b91709ebac18abf7a2bb9d391cdd9d058d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
